import { TStudentList, TTutorResult } from "types/index";

export const hardQuizzes = [
  {
    id: 1,
    uid: 9,
    title: "General Knowledge",
    subTitle: "Test your history knowledge",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 2,
    uid: 10,
    title: "Books",
    subTitle: "Test your knowledge of books",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 3,
    uid: 11,
    title: "Film",
    subTitle: "Test your knowledge of films",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 4,
    uid: 12,
    title: "Music",
    subTitle: "Test your knowledge of music",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 5,
    uid: 13,
    title: "Musicals & Theatres",
    subTitle: "Test your knowledge of musicals & theatres",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 6,
    uid: 14,
    title: "Television",
    subTitle: "Test your knowledge of television",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 7,
    uid: 15,
    title: "Video Games",
    subTitle: "Test your knowledge of video games",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 8,
    uid: 16,
    title: "Board Games",
    subTitle: "Test your knowledge of board games",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 9,
    uid: 17,
    title: "Science & Nature",
    subTitle: "Test your knowledge of science & nature",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 10,
    uid: 18,
    title: "Computers",
    subTitle: "Test your knowledge of computers",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 11,
    uid: 19,
    title: "Mathematics",
    subTitle: "Test your knowledge of mathematics",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 12,
    uid: 20,
    title: "Mythology",
    subTitle: "Test your knowledge of mythology",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 13,
    uid: 21,
    title: "Sports",
    subTitle: "Test your knowledge of sports",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 14,
    uid: 22,
    title: "Geography",
    subTitle: "Test your knowledge of geography",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 15,
    uid: 23,
    title: "History",
    subTitle: "Test your knowledge of history",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 16,
    uid: 24,
    title: "Politics",
    subTitle: "Test your knowledge of politics",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 17,
    uid: 25,
    title: "Art",
    subTitle: "Test your knowledge of art",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 18,
    uid: 26,
    title: "Celebrities",
    subTitle: "Test your knowledge of celebrities",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 19,
    uid: 27,
    title: "Animals",
    subTitle: "Test your knowledge of animals",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 20,
    uid: 28,
    title: "Vehicles",
    subTitle: "Test your knowledge of vehicles",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 21,
    uid: 29,
    title: "Comics",
    subTitle: "Test your knowledge of comics",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 22,
    uid: 30,
    title: "Gadgets",
    subTitle: "Test your knowledge of gadgets",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 23,
    uid: 31,
    title: "Anime & Manga",
    subTitle: "Test your knowledge of anime & manga",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
  {
    id: 24,
    uid: 32,
    title: "Cartoon & Animations",
    subTitle: "Test your knowledge of cartoons & animations",
    difficult: "hard",
    type: "multiple",
    info: ["hard", "multiple choices"],
    image: "",
  },
];

export const mediumQuizzes = [
  {
    id: 1,
    uid: 9,
    title: "General Knowledge",
    subTitle: "Test your history knowledge",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 2,
    uid: 10,
    title: "Books",
    subTitle: "Test your knowledge of books",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 3,
    uid: 11,
    title: "Film",
    subTitle: "Test your knowledge of films",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 4,
    uid: 12,
    title: "Music",
    subTitle: "Test your knowledge of music",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 5,
    uid: 13,
    title: "Musicals & Theatres",
    subTitle: "Test your knowledge of musicals & theatres",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 6,
    uid: 14,
    title: "Television",
    subTitle: "Test your knowledge of television",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 7,
    uid: 15,
    title: "Video Games",
    subTitle: "Test your knowledge of video games",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 8,
    uid: 16,
    title: "Board Games",
    subTitle: "Test your knowledge of board games",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 9,
    uid: 17,
    title: "Science & Nature",
    subTitle: "Test your knowledge of science & nature",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 10,
    uid: 18,
    title: "Computers",
    subTitle: "Test your knowledge of computers",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 11,
    uid: 19,
    title: "Mathematics",
    subTitle: "Test your knowledge of mathematics",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 12,
    uid: 20,
    title: "Mythology",
    subTitle: "Test your knowledge of mythology",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 13,
    uid: 21,
    title: "Sports",
    subTitle: "Test your knowledge of sports",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 14,
    uid: 22,
    title: "Geography",
    subTitle: "Test your knowledge of geography",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 15,
    uid: 23,
    title: "History",
    subTitle: "Test your knowledge of history",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 16,
    uid: 24,
    title: "Politics",
    subTitle: "Test your knowledge of politics",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 17,
    uid: 25,
    title: "Art",
    subTitle: "Test your knowledge of art",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 18,
    uid: 26,
    title: "Celebrities",
    subTitle: "Test your knowledge of celebrities",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 19,
    uid: 27,
    title: "Animals",
    subTitle: "Test your knowledge of animals",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 20,
    uid: 28,
    title: "Vehicles",
    subTitle: "Test your knowledge of vehicles",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 21,
    uid: 29,
    title: "Comics",
    subTitle: "Test your knowledge of comics",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 22,
    uid: 30,
    title: "Gadgets",
    subTitle: "Test your knowledge of gadgets",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 23,
    uid: 31,
    title: "Anime & Manga",
    subTitle: "Test your knowledge of anime & manga",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
  {
    id: 24,
    uid: 32,
    title: "Cartoon & Animations",
    subTitle: "Test your knowledge of cartoons & animations",
    difficult: "medium",
    type: "multiple",
    info: ["medium", "multiple choices"],
    image: "",
  },
];

export const easyQuizzes = [
  {
    id: 1,
    uid: 9,
    title: "General Knowledge",
    subTitle: "Test your history knowledge",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 2,
    uid: 10,
    title: "Books",
    subTitle: "Test your knowledge of books",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 3,
    uid: 11,
    title: "Film",
    subTitle: "Test your knowledge of films",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 4,
    uid: 12,
    title: "Music",
    subTitle: "Test your knowledge of music",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 5,
    uid: 13,
    title: "Musicals & Theatres",
    subTitle: "Test your knowledge of musicals & theatres",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 6,
    uid: 14,
    title: "Television",
    subTitle: "Test your knowledge of television",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 7,
    uid: 15,
    title: "Video Games",
    subTitle: "Test your knowledge of video games",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 8,
    uid: 16,
    title: "Board Games",
    subTitle: "Test your knowledge of board games",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 9,
    uid: 17,
    title: "Science & Nature",
    subTitle: "Test your knowledge of science & nature",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 10,
    uid: 18,
    title: "Computers",
    subTitle: "Test your knowledge of computers",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 11,
    uid: 19,
    title: "Mathematics",
    subTitle: "Test your knowledge of mathematics",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 12,
    uid: 20,
    title: "Mythology",
    subTitle: "Test your knowledge of mythology",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 13,
    uid: 21,
    title: "Sports",
    subTitle: "Test your knowledge of sports",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 14,
    uid: 22,
    title: "Geography",
    subTitle: "Test your knowledge of geography",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 15,
    uid: 23,
    title: "History",
    subTitle: "Test your knowledge of history",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 16,
    uid: 24,
    title: "Politics",
    subTitle: "Test your knowledge of politics",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 17,
    uid: 25,
    title: "Art",
    subTitle: "Test your knowledge of art",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 18,
    uid: 26,
    title: "Celebrities",
    subTitle: "Test your knowledge of celebrities",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 19,
    uid: 27,
    title: "Animals",
    subTitle: "Test your knowledge of animals",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 20,
    uid: 28,
    title: "Vehicles",
    subTitle: "Test your knowledge of vehicles",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 21,
    uid: 29,
    title: "Comics",
    subTitle: "Test your knowledge of comics",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 22,
    uid: 30,
    title: "Gadgets",
    subTitle: "Test your knowledge of gadgets",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 23,
    uid: 31,
    title: "Anime & Manga",
    subTitle: "Test your knowledge of anime & manga",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
  {
    id: 24,
    uid: 32,
    title: "Cartoon & Animations",
    subTitle: "Test your knowledge of cartoons & animations",
    difficult: "easy",
    type: "multiple",
    info: ["easy", "multiple choices"],
    image: "",
  },
];

export const students: TStudentList[] = [
  {
    Name: "João",
    Group: "Level 01",
    Average: "80%",
    Email: "joao@example.com",
    Phone: "+55 11 1234-5678",
    Photo: "",
  },
  {
    Name: "Maria",
    Group: "Level 02",
    Average: "90%",
    Email: "maria@example.com",
    Phone: "+55 11 9876-5432",
    Photo: "",
  },
  {
    Name: "Pedro",
    Group: "Level 01",
    Average: "70%",
    Email: "pedro@example.com",
    Phone: "+55 11 8765-4321",
    Photo: "",
  },
  {
    Name: "Ana",
    Group: "Level 03",
    Average: "85%",
    Email: "ana@example.com",
    Phone: "+55 11 2345-6789",
    Photo: "",
  },
  {
    Name: "Ana Maria",
    Group: "Level 03",
    Average: "85%",
    Email: "ana@example.com",
    Phone: "+55 11 2345-6789",
    Photo: "",
  },
];

export const TutorResults: TTutorResult[] = [
  { name: "Joao", quiz: "History", score: "7/10" },
  { name: "Maria", quiz: "Math", score: "9/10" },
  { name: "Pedro", quiz: "Science", score: "5/10" },
  { name: "Ana", quiz: "Literature", score: "8/10" },
  { name: "Carlos", quiz: "Geography", score: "6/10" },
  { name: "Laura", quiz: "Biology", score: "8/10" },
  { name: "Rafael", quiz: "Chemistry", score: "4/10" },
  { name: "Mariana", quiz: "Physics", score: "7/10" },
  { name: "Gabriel", quiz: "Art", score: "9/10" },
  { name: "Isabel", quiz: "Music", score: "6/10" },
];

export const example = {
  category: "categoryName",
  description: "description here",
  id: "id here",
  image: "",
  questions: [
    {
      answer01: "a",
      answer02: "b",
      answer03: "c",
      answer04: "d",
      questionTitle: "questionTitle",
      rightAnswer: "same as answer01",
    },
  ],
  title: "quizTitle",
  type: "Multiple",
};

export const ToFExample = {
  id: "id here",
  category: "categoryName",
  title: "quizTitle",
  type: "TrueOrFalse",
  description: "",
  image: "",
  date: "added date in this format: 1716835a740060",
  questions: [
    {
      questionTitle: "questionTitle",
      rightAnswer: "boolean",
    },
  ],
};

export const FillTheBlankExample = {
  id: "id here",
  category: "categoryName",
  title: "quizTitle",
  type: "FillTheBlanks",
  description: "",
  image: "",
  date: "added date in this format: 1716835a740060",
  questions: [
    {
      questionTitle: "This watch is expensive.",
      rightAnswer: ["watch"],
      spitedPhrase: ["This", "is", "expensive."],
    },
  ],
};
